<<<<<<< HEAD
# Generated by Django 4.2 on 2023-05-16 12:42
=======
# Generated by Django 4.2 on 2023-05-16 12:43
>>>>>>> origin/main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
